CREATE TABLE `ziniosblog`.`zblog_blog` (
  `ID` INT NOT NULL auto_increment,
  `CONTENT` VARCHAR(2000) NULL,
  `BLOG_STATUS` VARCHAR(10) NOT NULL,
  `BLOG_COMMENT_COUNT` INT NOT NULL,
  `VERSION` INT NOT NULL,
  `CREATED_BY` VARCHAR(30) NOT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL,
  `MODIFIED_BY` VARCHAR(30) NULL,
  `MODIFIED_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE TABLE `zblog_blog_comment_history` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BLOG_ID` int(11) NOT NULL,
  `COMMENT` varchar(1000) DEFAULT NULL,
  `CREATED_BY` varchar(30) NOT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `BLOG_ID_FK_idx` (`BLOG_ID`),
  CONSTRAINT `BLOG_ID_FK` FOREIGN KEY (`BLOG_ID`) REFERENCES `zblog_blog` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


